import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="main-header">
          <div className="link-wrapper">
            <Link href={"/"} className="link">
              Home
            </Link>
            <Link href={"/users"} className="link">
              Users
            </Link>
            <Link href={"/productsList"} className="link">
              Products (client side)
            </Link>
            <Link href={"/products"} className="link">
              Products (server side)
            </Link>
            <Link href={"/studentsList"} className="link">
              Students List
            </Link>
            <Link href={"/about"} className="link">
              About
            </Link>
            <Link href={"/login"} className="link">
              Login
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
